export enum PermissionCode {
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_DELETE = 'USER_DELETE',

    ROLE_CREATE = 'ROLE_CREATE',
    ROLE_UPDATE = 'ROLE_UPDATE',

    PERMISSION_ASSIGN = 'PERMISSION_ASSIGN',

    WORK_SPACE_CREATE = 'WORK_SPACE_CREATE',
    WORK_SPACE_UPDATE = 'WORK_SPACE_UPDATE',
    WORK_SPACE_DELETE = 'WORK_SPACE_DELETE',
}
